---
# tasks file for r_install_docker
- name: "install prereq software, cretae group and install docker"
  block:
          #  - name: "Update all packages to their latest version"
          #    ansible.builtin.apt:
          #      name: "*"
          #      state: latest
          #      update_cache: true

  - name: "Install prereq software"
    ansible.builtin.apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release

  - name: "add docker apt key"
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
      keyring: /etc/apt/trusted.gpg.d/docker.gpg

  - name: "set up repository"
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/debian/ bullseye stable
#      repo: deb [arch=arm64 https://download.docker.com/linux/debian bullseye stable
      state: present
      filename: docker.list

  - name: "Install docker software"
    ansible.builtin.apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: "Ensure docker service is started and enabled"
    ansible.builtin.systemd:
      name: docker.service
      state: started
      enabled: true

  - name: "Ensure containerd service is started and enabled"
    ansible.builtin.systemd:
      name: containerd.service
      state: started
      enabled: true

  - name: "Ensure group docker exists"
    ansible.builtin.group:
      name: docker
      state: present

  - name: "Ensure Dir for docker data exists"
    ansible.builtin.file:
      path: /data/docker
      state: directory
      group: 'docker'
      mode: '0775'

  rescue:
    - name: "fail"
      ansible.builtin.debug:
        msg: "install docker failed"

  tags:
    - install_docker

  become: true
  become_user: root
